services:
  app:
    build:
      context: .
      dockerfile: docker/prod/Dockerfile
    environment:
      APP_ENV: production

  nginx:
    image: nginx:alpine
    volumes:
      - ./docker/prod/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

