services:
  app:
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    volumes:
      - ./src:/var/www
    working_dir: /var/www
    command: php-fpm
    environment:
      APP_ENV: local

  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./app:/var/www
      - ./docker/dev/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: mplus
      POSTGRES_USER: mplus
      POSTGRES_PASSWORD: S3cr#t!2e
    ports:
      - "5432:5432"


